services:
  mock_api:
    build:
      context: ..
      dockerfile: mock_api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../mock_api/src:/app
    env_file:
      - ../mock_api/.env
    environment:
      - POETRY_VERSION=1.7.1
      - PYTHON_VERSION=3.11.11
    command: ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wishlist
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ..
      dockerfile: wishlist_developer_test/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - ../wishlist_developer_test/.env.docker
    command: ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000"]

volumes:
  pgdata:
